application: whaler-on-fleek
version: master
runtime: python27
api_version: 1
threadsafe: yes
#automatic_scaling:
#  min_idle_instances: 1

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
